name: Build and test

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build-check:
    permissions:
      contents: read
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    uses: Shane32/SharedWorkflows/.github/workflows/build-check.yml@v3
    with:
      dotnet_folder: '.'
      dotnet_build_runner: ${{ matrix.os }}
      dotnet_version: |
        6.0.x
        8.0.x
        10.0.x
      coveralls: ${{ matrix.os == 'ubuntu-latest' }}
      data_collector: ${{ matrix.os == 'ubuntu-latest' && 'XPlat Code Coverage' || '' }}
