name: Build and test

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build-check-windows:
    permissions:
      contents: read
      pull-requests: write
    uses: Shane32/SharedWorkflows/.github/workflows/build-check.yml@v3
    with:
      dotnet_folder: '.'
      dotnet_build_runner: windows-latest
      dotnet_version: |
        6.0.x
        8.0.x
        10.0.x
      format: false

  build-check-ubuntu:
    permissions:
      contents: read
      pull-requests: write
    uses: Shane32/SharedWorkflows/.github/workflows/build-check.yml@v3
    with:
      dotnet_folder: '.'
      dotnet_version: |
        6.0.x
        8.0.x
        10.0.x
      coveralls: true
      data_collector: 'XPlat Code Coverage'
